
const FETCH_PRODUCTS_REQUESTED = "FETCH_PRODUCTS_REQUESTED ";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

const FETCH_SINGLE_PRODUCT_REQUESTED = "FETCH_SINGLE_PRODUCT_REQUESTED ";
const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
const FETCH_SINGLE_PRODUCT_FAILURE = "FETCH_SINGLE_PRODUCT_FAILURE";

const FETCH_SIMILAR_PRODUCTS_REQUESTED = "FETCH_SIMILAR_PRODUCTS_REQUESTED ";
const FETCH_SIMILAR_PRODUCTS_SUCCESS = "FETCH_SIMILAR_PRODUCTS_SUCCESS";
const FETCH_SIMILAR_PRODUCTS_FAILURE = "FETCH_SIMILAR_PRODUCTS_FAILURE";

const GET_ITEMS_FROM_CART = "GET_ITEMS_FROM_CART";
const ADD_ITEM_TO_CART = "ADD_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
const REMOVE_ALL_ITEMS_FROM_CART = "REMOVE_ALL_ITEMS_FROM_CART";
const CLEAR_CART = "CLEAR_CART";


export {
    FETCH_PRODUCTS_REQUESTED,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILURE,
    FETCH_SINGLE_PRODUCT_REQUESTED,
    FETCH_SINGLE_PRODUCT_SUCCESS,
    FETCH_SINGLE_PRODUCT_FAILURE,
    FETCH_SIMILAR_PRODUCTS_REQUESTED,
    FETCH_SIMILAR_PRODUCTS_SUCCESS,
    FETCH_SIMILAR_PRODUCTS_FAILURE,
    GET_ITEMS_FROM_CART,
    ADD_ITEM_TO_CART,
    REMOVE_ITEM_FROM_CART,
    REMOVE_ALL_ITEMS_FROM_CART,
    CLEAR_CART
};